### ISSUE TITLE
AssertionError: Invalid type <class 'NoneType'> for key LR_NOISE; valid types = {<class 'str'>, <class 'bool'>, <class 'list'>, <class 'float'>, <class 'int'>, <class 'tuple'>}

### ISSUE THREAD

**Issue by pawopawo** [microsoft/Cream#11]
Traceback (most recent call last):
  File "./tools/main.py", line 13, in <module>
    from lib.config import cfg
  File "/opt/tiger/xiaxin/work/Cream/tools/../lib/config.py", line 74, in <module>
    __C.LR_NOISE = None
  File "/home/tiger/.local/lib/python3.7/site-packages/yacs/config.py", line 158, in __setattr__
    type(value), name, _VALID_TYPES
  File "/home/tiger/.local/lib/python3.7/site-packages/yacs/config.py", line 525, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key LR_NOISE; valid types = {<class 'str'>, <class 'bool'>, <class 'list'>, <class 'float'>, <class 'int'>, <class 'tuple'>}

**Comment by Z7zuqer** [comment]
Hi,

Thanks for your interest in our project!

We've settle the issue. This error comes from a useless parameter, and we've removed it.

Best,
Hao.

**Comment by Z7zuqer** [comment]
Hi,

Could you share the environment variables with me?

I have checked that without delete, this codes run correctly.

Best,
Hao.
