### ISSUE TITLE
AttributeError: 'MetaMatchingNetwork' object has no attribute 'TTA'

### ISSUE THREAD

**Issue by pawopawo** [microsoft/Cream#13]
Traceback (most recent call last):
  File "tools/train.py", line 239, in <module>
    main()
  File "tools/train.py", line 222, in main
    local_rank=args.local_rank, logger=logger)
  File "/Cream/tools/../lib/core/train.py", line 168, in validate
    reduce_factor = cfg.TTA
AttributeError: 'MetaMatchingNetwork' object has no attribute 'TTA'

**Comment by Z7zuqer** [comment]
Hi,

Have you installed the environments as README?(the same problem in your previous issue)

Best,
Hao.
