### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu!

### ISSUE THREAD

**Issue by Ema1997** [microsoft/Cream#2]
When I tried to resume training from the checkpoint file, I encountered with a runtimeError.
The error message is as below: 
```
Traceback (most recent call last):
  File "tools/train.py", line 243, in <module>
    main()
  File "tools/train.py", line 218, in main
    train_metrics = train_epoch(epoch, model, loader_train, optimizer,
  File "/opt/tiger/cream/tools/../lib/core/train.py", line 68, in train_epoch
    optimizer.step()
  File "/usr/local/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 67, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/optim/sgd.py", line 106, in step
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cpu!
```
Part of my train.yaml is as follows: 
``` shell script
AUTO_RESUME: True
DATA_DIR: '/opt/tiger/data/ImageNet'
MODEL: 'Supernet_Training'
RESUME_PATH: './experiments/workspace/train/11041800-Supernet_Training/checkpoint-0.pth.tar'
SAVE_PATH: './experiments/workspace/train'
```
How can I deal with this error and resume training using the checkpoint file?

**Comment by Ema1997** [comment]
I solved this problem through modified the order of the codes.
```py
model_est = FlopsEst(model)

    # create optimizer
    optimizer = create_optimizer_supernet(cfg, model, USE_APEX)

    # create learning rate scheduler
    lr_scheduler, num_epochs = create_supernet_scheduler(cfg, optimizer)

    model = model.cuda()

    # optionally resume from a checkpoint
    resume_epoch = None
    optimizer_state = None
    if cfg.AUTO_RESUME:
        optimizer_state, resume_epoch = resume_checkpoint(
            model, cfg.RESUME_PATH)
```
In other words, I create the lr_scheduler and the optimizer before loading the model from the checkpoint file. Also, I transfer the model to cuda devices before loading.
